In [1]:
22==21

False

In [4]:
a=2
b=2
a>b

False

In [5]:
a=True
b=False
b>a

True

In [10]:
a and b

False

In [11]:
a or b

True

In [13]:
not a

True

In [20]:
import numpy as np
h=np.array([18.32,20.44,10.75,9.50])
yh=np.array([14.0,24.0,14.25,9.5])



In [21]:
len(h)

4

In [16]:
h.shape

(4,)

In [17]:
h.size

4

In [22]:
print(h>=18)

[ True  True False False]


In [23]:
print(h[h>=18])

[18.32 20.44]


In [24]:
print(h<yh)

[False  True  True False]


In [25]:
print(h[h<yh])

[20.44 10.75]


In [27]:
n1=h/2
print(n1)

[ 9.16  10.22   5.375  4.75 ]


In [29]:
n2=h+yh
print(n2)

[32.32 44.44 25.   19.  ]


In [30]:
mk=18
yk=14
print(mk>10 and mk<18)

False


In [32]:
print(mk>10 or mk<18)

True


In [33]:
x=8
y=9
not(not(x<3)and not(y>14 or y>10))


False

In [34]:
h

array([18.32, 20.44, 10.75,  9.5 ])

In [36]:
(h>15)and(h>10)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
np.logical_and(h>15,h>10)

array([ True,  True, False, False])

In [38]:
np.logical_or(h>15,h>10)

array([ True,  True,  True, False])

In [43]:
q=2
if q>=1:
    print('ok')
    print('House No',q)
    print('House No'+str(q))
    print(2+4)

    

ok
House No 2
House No2
6


In [45]:
w=200
if w>=400:
    print('ok')
    print('House No',q)
    print('House No'+str(q))
    print(2+4)
else:
    print("Invalid")

Invalid


In [46]:
import pandas as pd

In [49]:
data=pd.read_csv('NAVTTC_2.1.csv')

In [50]:
data

Unnamed: 0     Country    Capital  Area  Population
0         Pk    Pakistan  Islamabad   786       57574
1         Au  Austrailia     Sydney   546        9876
2         IN       India  New Dehli   123        9876
3         CH       China    Beijing   645        5432
4         AG  Afganistan      Kabul  8788        9654

In [55]:
data=pd.read_csv('NAVTTC_2.1.csv', index_col=0)

In [56]:
data

Country    Capital  Area  Population
Pk    Pakistan  Islamabad   786       57574
Au  Austrailia     Sydney   546        9876
IN       India  New Dehli   123        9876
CH       China    Beijing   645        5432
AG  Afganistan      Kabul  8788        9654

In [61]:
a1=data['Area']

In [62]:
a1

Pk     786
Au     546
IN     123
CH     645
AG    8788
Name: Area, dtype: int64

In [65]:

data.loc['Pk']

Country        Pakistan
Capital       Islamabad
Area                786
Population        57574
Name: Pk, dtype: object

In [66]:
data.iloc[2]

Country           India
Capital       New Dehli
Area                123
Population         9876
Name: IN, dtype: object

In [67]:
#Slicing
data.iloc[1:4]

Country    Capital  Area  Population
Au  Austrailia     Sydney   546        9876
IN       India  New Dehli   123        9876
CH       China    Beijing   645        5432

In [68]:
data.columns

Index(['Country', 'Capital', 'Area', 'Population'], dtype='object')

In [69]:
data.index

Index(['Pk', 'Au', 'IN', 'CH', 'AG'], dtype='object')

In [70]:
data['Area']>1000

Pk    False
Au    False
IN    False
CH    False
AG     True
Name: Area, dtype: bool

In [71]:
data[data['Area']>1000]

Country Capital  Area  Population
AG  Afganistan   Kabul  8788        9654