In [3]:
h=[1.76,1.87,1.88]
w=[60,70,80]
import numpy as np 
nph=np.array(h)
npw=np.array(w)
bmi=npw/nph**2
bmi

array([19.36983471, 20.01772999, 22.63467632])

In [4]:

bmi>20

array([False,  True,  True])

In [5]:
bmi[bmi>20]

array([20.01772999, 22.63467632])

In [6]:
h=[1.76,1.87,1.88]
w=[60,70,80]


In [7]:
type(nph)

numpy.ndarray

In [ ]:
nph[]