In [4]:
z=6
if z%2==0:
    print("Z is Divid by 2")
elif z%3==0:
    print("Z is Divid by 3")
else :
    print("Z is not Divid bye 2 or 3")


Z is Divid by 2


In [3]:
e=50.0
while e>1:
    e=e/4
    print(e)

12.5
3.125
0.78125


In [7]:
fam=[1.73,1.68,1.71,1.89]
for height in fam:
    print(height)

1.73
1.68
1.71
1.89


In [12]:
for i, height in enumerate(fam):
    print("index" + str(i)+":"+ str(height))

index0:1.73
index1:1.68
index2:1.71
index3:1.89


In [15]:
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


In [19]:
w={'Afghanistan':30.55,'Albania':2.77,'Algeria':39.21}
for key, value in w.items():
    print(key+"--"+str(value))

Afghanistan--30.55
Albania--2.77
Algeria--39.21


In [20]:
for each in w.keys():
    print(each,'keys')

Afghanistan keys
Albania keys
Algeria keys


In [22]:
for each in w.values():
    print(each,'values')

30.55 values
2.77 values
39.21 values


In [24]:
import numpy as np
np_h=np.array([1.73,1.68,1.71,1.89,1.79])
np_w=np.array([65.4,69.2,63.6,88.0,68.9])
bmi=np_w/np_h**2
for v in bmi:
    print(v)

21.85171572722109
24.518140589569164
21.750282138093777
24.635368550712467
21.503698386442373


In [25]:
print(bmi)

[21.85171573 24.51814059 21.75028214 24.63536855 21.50369839]


In [26]:
import numpy as np
np_h=np.array([1.73,1.68,1.71,1.89,1.79])
np_w=np.array([65.4,69.2,63.6,88.0,68.9])
meas =np.array([np_h,np_w])
for v in meas:
    print(v)

[1.73 1.68 1.71 1.89 1.79]
[65.4 69.2 63.6 88.  68.9]


In [27]:
meas

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 69.2 , 63.6 , 88.  , 68.9 ]])

In [30]:
import numpy as np
np_h=np.array([1.73,1.68,1.71,1.89,1.79])
np_w=np.array([65.4,69.2,63.6,88.0,68.9])
meas =np.array([np_h,np_w])
for v in np.nditer(meas):
    print(v)

1.73
1.68
1.71
1.89
1.79
65.4
69.2
63.6
88.0
68.9
