In [1]:
from sklearn import linear_model, metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('Real estate.csv')

In [12]:
df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [13]:
df.tail()

No  X1 transaction date  X2 house age  \
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9

In [ ]:
# for the X3 columns of X in data

In [39]:
x = df[['X3 distance to the nearest MRT station']]
y = df[['Y house price of unit area']] #[[]] dataframe form

In [40]:
x

X3 distance to the nearest MRT station
0                                  84.87882
1                                 306.59470
2                                 561.98450
3                                 561.98450
4                                 390.56840
..                                      ...
409                              4082.01500
410                                90.45606
411                               390.96960
412                               104.81010
413                                90.45606

[414 rows x 1 columns]

In [41]:
y

Y house price of unit area
0                          37.9
1                          42.2
2                          47.3
3                          54.8
4                          43.1
..                          ...
409                        15.4
410                        50.0
411                        40.6
412                        52.5
413                        63.9

[414 rows x 1 columns]

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1) # 0 (splitting) 

In [43]:
x_train.shape

(331, 1)

In [44]:
x_test.shape

(83, 1)

In [49]:
reg1 = LinearRegression(); # 1 (calling model)
reg1.fit(x_train, y_train); # 2 (training model)

In [50]:
reg1.coef_ # m = -0.0073 
# 3 (slope)

array([[-0.00729838]])

In [52]:
reg1.intercept_ # b = 46.4 
# 4 (intercept)

array([46.39816949])

In [55]:
y_test

Y house price of unit area
388                        27.3
102                        54.4
187                        22.0
162                        11.6
90                         45.4
..                          ...
322                        33.1
119                        59.6
245                        40.8
146                        52.2
360                        47.1

[83 rows x 1 columns]

In [58]:
y_pred = reg1.predict(x_test)
y_pred

array([[29.96267342],
       [44.98531652],
       [23.93247569],
       [16.71867802],
       [44.39830866],
       [33.86544487],
       [30.49069651],
       [37.89674077],
       [43.83752241],
       [13.47986196],
       [14.19213992],
       [43.64087417],
       [38.69789109],
       [45.25784016],
       [45.73798692],
       [33.38384677],
       [44.39830866],
       [42.50465821],
       [30.51779539],
       [44.28656756],
       [45.79323294],
       [28.37376531],
       [42.83058118],
       [44.50306739],
       [43.1048214 ],
       [36.07215343],
       [30.52397712],
       [45.6332257 ],
       [43.54765344],
       [16.60607864],
       [31.2365908 ],
       [41.54428355],
       [41.89944601],
       [45.6332257 ],
       [45.01499464],
       [15.76432744],
       [42.87481811],
       [43.36972481],
       [36.16572594],
       [16.71867802],
       [41.84782677],
       [38.03182646],
       [45.73798692],
       [30.72580648],
       [33.89873278],
       [35

In [59]:
reg1.score(x_test,y_test) #our model is 54% efficient

0.546483701256812

In [ ]:
# for all the columns of X in data

In [63]:
a = df.iloc[:,1:-1]
b = df[['Y house price of unit area']]

In [64]:
a

X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  
0       24.98298     121.54024  
1       24.98034     121.53951  
2       24.98746     121.54391  
3       24.98746     121.54391  
4       24.97937     121.54245  
..           ...           ...  
409     24.94155     121.50381  
410     24.97433     121.54310  
411     24.97923     121.53986  
412     24.96674     121.54067  
413     24.97433     121.54310  

[414 rows x 6 columns]

In [65]:
b

Y house price of unit area
0                          37.9
1                          42.2
2                          47.3
3                          54.8
4                          43.1
..                          ...
409                        15.4
410                        50.0
411                        40.6
412                        52.5
413                        63.9

[414 rows x 1 columns]

In [72]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.2, random_state=1) # 0 (splitting) 

In [73]:
a_train.shape

(331, 6)

In [74]:
b_test.shape

(83, 1)

In [75]:
reg1a = LinearRegression(); # 1 (calling model)
reg1a.fit(a_train, b_train); # 2 (training model)

In [76]:
reg1a.coef_ # m = -0.0073 
# 3 (slope)

array([[ 5.71714218e+00, -2.49326467e-01, -4.93769843e-03,
         1.07614509e+00,  2.27037100e+02, -3.56988335e+01]])

In [77]:
reg1a.intercept_ # b = 46.4 
# 4 (intercept)

array([-12796.1176849])

In [78]:
b_test

Y house price of unit area
388                        27.3
102                        54.4
187                        22.0
162                        11.6
90                         45.4
..                          ...
322                        33.1
119                        59.6
245                        40.8
146                        52.2
360                        47.1

[83 rows x 1 columns]

In [80]:
b_pred = reg1a.predict(a_test)
b_pred

array([[34.79742428],
       [47.46521888],
       [20.92649905],
       [12.44066887],
       [42.96379361],
       [34.74573027],
       [31.04247971],
       [45.54751177],
       [37.82067836],
       [13.75947347],
       [11.93297924],
       [38.39381127],
       [31.93092108],
       [45.46667102],
       [50.93522403],
       [36.30036154],
       [44.39307916],
       [45.09388121],
       [29.88922181],
       [43.9352825 ],
       [51.50141664],
       [28.29865035],
       [40.17210353],
       [46.98674853],
       [45.65710115],
       [27.92775475],
       [30.98685655],
       [47.60814939],
       [46.06040453],
       [15.1867402 ],
       [33.78086918],
       [34.84166227],
       [42.27618027],
       [44.84930889],
       [48.12439262],
       [12.87264524],
       [41.12137596],
       [41.15743598],
       [39.01226777],
       [13.32063367],
       [38.96468765],
       [24.28892917],
       [54.5683122 ],
       [36.63436327],
       [35.05528108],
       [38

In [81]:
reg1a.score(a_test,b_test) #our model is 70% efficient

0.7034608498767054