In [4]:
from sklearn import linear_model, metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('Real Estate.csv')

In [54]:
df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [55]:
x = df[['X3 distance to the nearest MRT station']]
y = df[['Y house price of unit area']]

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)    # 0 (splitting)

In [57]:
x_train.shape

(331, 1)

In [58]:
x_test.shape

(83, 1)

In [59]:
reg1 = LinearRegression();         # 1   (Calling Model)
reg1.fit(x_train, y_train);        # 2   (TRaining Model)


In [60]:
reg1.coef_                          # 3 (slope)

array([[-0.00729838]])

In [61]:
reg1.intercept_                     # 4 (intercept)

array([46.39816949])

In [62]:
y_pred = reg1.predict(x_test)        # 5 (Predicted o/p)
y_pred

array([[29.96267342],
       [44.98531652],
       [23.93247569],
       [16.71867802],
       [44.39830866],
       [33.86544487],
       [30.49069651],
       [37.89674077],
       [43.83752241],
       [13.47986196],
       [14.19213992],
       [43.64087417],
       [38.69789109],
       [45.25784016],
       [45.73798692],
       [33.38384677],
       [44.39830866],
       [42.50465821],
       [30.51779539],
       [44.28656756],
       [45.79323294],
       [28.37376531],
       [42.83058118],
       [44.50306739],
       [43.1048214 ],
       [36.07215343],
       [30.52397712],
       [45.6332257 ],
       [43.54765344],
       [16.60607864],
       [31.2365908 ],
       [41.54428355],
       [41.89944601],
       [45.6332257 ],
       [45.01499464],
       [15.76432744],
       [42.87481811],
       [43.36972481],
       [36.16572594],
       [16.71867802],
       [41.84782677],
       [38.03182646],
       [45.73798692],
       [30.72580648],
       [33.89873278],
       [35

In [63]:
y_test

Y house price of unit area
388                        27.3
102                        54.4
187                        22.0
162                        11.6
90                         45.4
..                          ...
322                        33.1
119                        59.6
245                        40.8
146                        52.2
360                        47.1

[83 rows x 1 columns]

In [64]:
reg1.score(x_test, y_test)             # 0

0.546483701256812