In [25]:
height = [1.73,1.68,1.71,1.89,1.79]
weight = [65.4,59.2,63.6,88.4,68.7]
print(height)
height

[1.73, 1.68, 1.71, 1.89, 1.79]


[1.73, 1.68, 1.71, 1.89, 1.79]

In [2]:
weight/height ** 2 # here maths operations are not possible

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)

In [7]:
# 1D numpy array
bmi = np_weight/np_height ** 2 
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [19]:
np.array([2,1.0,"is",True])

array(['2', '1.0', 'is', 'True'], dtype='<U32')

In [10]:
# Different types: different behavior()
python_list = [1,2,3]
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [20]:
# Different types: different behavior()
numpy_array = np.array([1,2,3])
# numpy_array + numpy_array
numpy_array*2

array([2, 4, 6])

In [22]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [21]:
bmi[1]

20.97505668934241

In [23]:
# numpy subsetting
bmi>23

array([False, False, False,  True, False])

In [24]:
bmi[bmi>23]

array([24.7473475])

In [28]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
print(type(np_height))
print(type(np_weight))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [31]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                 [65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [34]:
np_2d.shape # attribute (row,column)

(2, 5)

In [37]:
np_2d[0] # this is called subsetting

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [38]:
np.array([[1.73,1.68,1.71,1.89,1.79],
          [65.4,59.2,63.6,88.4,"68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [40]:
np_2d[0][2]

1.71

In [41]:
np_2d[0,2]

1.71

In [43]:
np_2d[:,1:3] #3 is explicit, always the last one excluded. Gives all rows, 1 and 2 column

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [44]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
np_city=np.array(([]))

In [ ]:
np_city[:,0].sort()

In [ ]:
np.corrcoef(np_city[:,0], np_city[:,1])

In [45]:
weight=np.round(np.random.normal(60.32,15,5000),2)

In [46]:
weight

array([51.88, 47.99, 77.42, ..., 37.91, 62.29, 78.31])