In [1]:
# comparator of integers
1==1

True

In [6]:
1!=1

False

In [3]:
#Comparison of strings
'A' == 'A'

True

In [7]:
a=2
~a

-3

In [8]:
c=6
d=30
c>d

False

In [9]:
a=3
a>=3

True

In [11]:
a = 'Google'
b = 'google'
a == b

False

In [13]:
a = 'google'
b = 'google'
a == b

True

In [25]:
a = True
b = False
a == b

False

In [26]:
a > b # a=1 and b=0

True

In [32]:
a = True
b = False
a and b # any one false gives output false

False

In [33]:
2.0==2

True

In [34]:
a or b

True

In [37]:
# not is unary operator and takes single operator
not a

False

In [38]:
2*2 == 4

True

In [39]:
True == True

True

In [41]:
1.0==True

True

In [42]:
False == 0

True

In [43]:
import numpy as np
my_house = np.array([18.0,20.0,10.75,9.50])
your_house = np.array([14.0,24.0,14.25,9.0])


In [44]:
len(my_house)

4

In [45]:
my_house.shape

(4,)

In [46]:
my_house.size

4

In [51]:
print(my_house>=18)

[ True  True False False]


In [53]:
print(my_house[my_house>=18])
print(my_house[True])

[18. 20.]
[[18.   20.   10.75  9.5 ]]


In [52]:
print(my_house<your_house)

[False  True  True False]


In [54]:
print(my_house[my_house<your_house])

[20.   10.75]


In [55]:
new1 = my_house / 2
new1 #if strimng in my_house then error returned

array([ 9.   , 10.   ,  5.375,  4.75 ])

In [57]:
new2 = my_house + your_house
new2

array([32. , 44. , 25. , 18.5])

In [58]:
True and True

True

In [59]:
True and False

False

In [60]:
True or False

True

In [61]:
not True

False

In [62]:
my_kitchen = 18.0
your_kitchen = 14.0
print(my_kitchen > 10 and my_kitchen < 18)

False


In [63]:
print(my_kitchen > 10 or my_kitchen < 18)

True


In [65]:
x=8
y=9

In [66]:
not(not(x<3) and not (y>14 or y>10))

False

In [70]:
(my_house > 15)

array([ True,  True, False, False])

In [71]:
my_house > 10

array([ True,  True,  True, False])

In [80]:
(list(my_house >15)) and (list(my_house > 10)) #?????????

[True, True, True, False]

In [74]:
np.logical_and (my_house > 15,my_house > 10)

array([ True,  True, False, False])

In [75]:
np.logical_or(my_house > 15,my_house > 10)

array([ True,  True,  True, False])

In [79]:
np.logical_not(my_house > 15)

array([False, False,  True,  True])

In [85]:
# conditional statements
q=-1
if q <=1:
    print('not ok'+str(q)) #string is necessary for concatenation

not ok-1


In [92]:
q=1
if q>0:
    print("q>0")
elif q<0:
    print("q<0")
#else:
 #   print("It is equal to 0")

q>0


In [96]:
import pandas as pd

In [100]:
data=pd.read_csv("2.1.csv")
print(data)

  Unnamed: 0      country    capital    area  population
0         PK     pakistan  islamabad     789      456789
1         AU    australia     sydney     456      123456
2         IN        india  new delhi    6789      789789
3         CH        china     bejing  456456     7891011
4         AG  afghanistan      kabul     123      123123


In [103]:
data = pd.read_csv("2.1.csv")

In [104]:
data

Unnamed: 0      country    capital    area  population
0         PK     pakistan  islamabad     789      456789
1         AU    australia     sydney     456      123456
2         IN        india  new delhi    6789      789789
3         CH        china     bejing  456456     7891011
4         AG  afghanistan      kabul     123      123123

In [105]:
data = pd.read_csv("2.1.csv", index_col=0)

In [106]:
data

country    capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123

In [107]:
data=pd.read_csv('2.1.csv', index_col=0)

In [109]:
a1=data['capital']
a1

PK    islamabad
AU       sydney
IN    new delhi
CH       bejing
AG        kabul
Name: capital, dtype: object

In [110]:
data

country    capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123

In [114]:
data.loc['AU']

country       australia
capital          sydney
area                456
population       123456
Name: AU, dtype: object

In [117]:
data.loc['AG']

country       afghanistan
capital             kabul
area                  123
population         123123
Name: AG, dtype: object

In [118]:
data.iloc[4]

country       afghanistan
capital             kabul
area                  123
population         123123
Name: AG, dtype: object

In [124]:
data[1:3]

country    capital  area  population
AU  australia     sydney   456      123456
IN      india  new delhi  6789      789789

In [126]:
data[:2]

country    capital  area  population
PK   pakistan  islamabad   789      456789
AU  australia     sydney   456      123456

In [127]:
data[2:]

country    capital    area  population
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123

In [125]:
data[2:4]

country    capital    area  population
IN   india  new delhi    6789      789789
CH   china     bejing  456456     7891011

In [128]:
data

country    capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123

In [131]:
data['PK':'IN']

country    capital  area  population
PK   pakistan  islamabad   789      456789
AU  australia     sydney   456      123456
IN      india  new delhi  6789      789789

In [140]:
data[['country','area']]

country    area
PK     pakistan     789
AU    australia     456
IN        india    6789
CH        china  456456
AG  afghanistan     123

In [137]:
data.columns

Index(['country', 'capital', 'area', 'population'], dtype='object')

In [138]:
data.index

Index(['PK', 'AU', 'IN', 'CH', 'AG'], dtype='object')

In [148]:
data

country    capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123

In [146]:
data['area']>1000

PK    False
AU    False
IN     True
CH     True
AG    False
Name: area, dtype: bool

In [145]:
data[data['area']>1000]

country    capital    area  population
IN   india  new delhi    6789      789789
CH   china     bejing  456456     7891011

In [147]:
data.iloc[1:3]

country    capital  area  population
AU  australia     sydney   456      123456
IN      india  new delhi  6789      789789

In [150]:
data = pd.read_csv("2.1.csv")

In [151]:
data

country    capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china     bejing  456456     7891011
AG  afghanistan      kabul     123      123123