In [1]:
import numpy
numpy.__version__

'1.18.5'

In [95]:
# 02.01-Understanding-Data-Types
# https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb

In [2]:
import numpy as np

In [3]:
# np.<TAB>

In [4]:
np?

In [5]:
result=0
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [6]:
x= 4
x = "four"

In [8]:
# struct _longobject{
    
#     long ob_refcnt;
#     PyTypeObject *ob_type;
#     size_t
#     ......
# }

In [10]:
l=list(range(10))
type(l[0])

int

In [12]:
l2=[str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(l2[0])

str

In [14]:
l3=[True,"2",3.0,4]
[type(item) for item in l3]

[bool, str, float, int]

In [17]:
import array #python buil in data type array. It is ab abstraction of python
l=list(range(10))
a=array.array('i',l)
a #if one is float and all int then all will convert to int

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
import array #python buil in data type array. It is ab abstraction of python
l=list(range(10))
a=array.array('i',[3.14,4,2,3])
a #if one is float and all int then all will convert to int

TypeError: integer argument expected, got float

In [20]:
np.array([3.14,4,2,3]) # it converted all integers to float if one value is float

array([3.14, 4.  , 2.  , 3.  ])

In [21]:
np.array([1,2,3,4], dtype='float32') #define datatype yourself

array([1., 2., 3., 4.], dtype=float32)

In [23]:
np.array([range(i,i+3) for i in [2,4,6]]) # starts from 2 till 2+3=5 i.e 4. Then second time it runs from 4 till 4+3=7 i.e 6

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.full((3,5),3.14) # rows=3, columns=5

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
np.full((3,5),np.pi) # rows=3, columns=5

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [32]:
np.arange(0,20,2) # like linspace in MATLAB. 2 is step size. 0 to 20 is range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
np.linspace(0,1,5) # 5 is number of values. (1-0)/5 = 0.25 = step size. 1 is inclusive. Divides values evenly

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.random.random((3,3)) 

array([[0.94993291, 0.04356152, 0.33559445],
       [0.09537551, 0.63546065, 0.27797338],
       [0.86230621, 0.33859438, 0.14148274]])

In [41]:
np.random.normal(0,1,(3,3)) # mean = 0 and standard deviation = 1. 3 x 3 = rows x columns

array([[-0.4389925 ,  0.39300129,  0.00952425],
       [ 0.67788503,  1.95724606, -0.68385957],
       [-0.52027825, -0.62486213,  0.55046438]])

In [44]:
np.random.randint(0,10,(3,3)) # randint for random integers and 0 to 10 is limit

array([[5, 8, 6],
       [1, 5, 0],
       [0, 9, 9]])

In [45]:
np.eye(3) # gives identitiy matrix. Always gives float 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [54]:
np.empty(3) # initializes values

array([5.35567160e-321, 1.16709769e-311, 1.16709769e-311])

In [64]:
import numpy as np
# seed for reproducibility. Same for all because seed is used
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print("x1:",x1)
print("x2:",x2)
print("x3:",x3)

x1: [5 0 3 3 7 9]
x2: [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3: [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [65]:
print("x3 dimensions:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 dimensions: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [67]:
print("dtype:",x3.dtype)

dtype: int32


In [68]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [69]:
x1

array([5, 0, 3, 3, 7, 9])

In [70]:
x1[0]

5

In [71]:
x1[4]

7

In [72]:
x1[-1]

9

In [73]:
x1[-2]

7

In [74]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [75]:
x2[0,0]

3

In [76]:
x2[2,0]

1

In [77]:
x2[2,-1]

7

In [78]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [81]:
x1[0]=3.14159 # by changing yourself float truncates to integer
x1

array([3, 0, 3, 3, 7, 9])

In [82]:
x=np.arange(10)

In [83]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x[:5]

array([0, 1, 2, 3, 4])

In [85]:
x[5:]

array([5, 6, 7, 8, 9])

In [86]:
x[4:7]

array([4, 5, 6])

In [87]:
x[::2]

array([0, 2, 4, 6, 8])

In [88]:
x[1::2]

array([1, 3, 5, 7, 9])

In [89]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [90]:
x[5::-2]

array([5, 3, 1])

In [91]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [92]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [93]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [96]:
x2[::-1,::-1] #last column changes first column. last row changes first row

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [97]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [98]:
print(x2[:,0])

[12  7  1]


In [100]:
print(x2[0,:])

[12  5  2  4]


In [101]:
print(x2[0])

[12  5  2  4]


In [102]:
print(x2[2])

[1 6 7 7]


In [104]:
#print(x2[[0]])

In [105]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [106]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [111]:
print(x2) # See 99 has also changed x2. So original content changes

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [112]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [114]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [115]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [127]:
grid = np.arange(1,10).reshape((3,3)) #reshapes it to 3 x 3. Otherwise 1D array will be displayed. Dont give range 1,9, error will be thrown bcoz 8 values are not right for 3x3
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [135]:
x = np.array([1,2,3])

x.reshape((1,3)) #converting x array to 2 dimensions

array([[1, 2, 3]])

In [130]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [136]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [137]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [139]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [140]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [141]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [148]:
# x is a matrix
# -x
# x//2
# x%2
# -(.5*x+1)**2
# np.add(x,2)
# abs(x) # for modulus
# x = np.array([1 - 4j,3-4j])
# np.abs(x) # for complex it finds 
# theta = np.linspace(0,np.pi,3)
# np.sin(theta)
# np.cos(theta)
# np.tan(theta)
