In [3]:
z = 9
if z % 2 == 0:
    print("z is divisible by 2")
elif z % 3 == 0:
    print("z is divisible by 3")
else:
    print("z is neither divisible by 2 nor by 3")

z is divisible by 3


In [1]:
error =50.0
while error >1:
    error = error / 4
    print(error)
    

12.5
3.125
0.78125


In [5]:
fam = [1.73,1.68,1.71,1.89]
print(fam[0])
print(fam[1])
print(fam[2])
print(fam[3])

1.73
1.68
1.71
1.89


In [15]:
fam = [1.73,1.68,1.71,1.89]
for height in fam:  #will have no indices
    print(height)

1.73
1.68
1.71
1.89


In [16]:
for index,height in enumerate(fam):
    print("index "+str(index)+": "+str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [17]:
for index,height in enumerate(fam): # enumerate will return indices
    print("index ",index,": ",height)

index  0 :  1.73
index  1 :  1.68
index  2 :  1.71
index  3 :  1.89


In [18]:
height in fam

True

In [24]:
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


In [35]:
for c in "family":
    if c == 'f':
        print(c.capitalize())
    else:
        print(c)

F
a
m
i
l
y


In [ ]:
for i in range(2,num):
    while num % i == 0:
        if num 

In [39]:
world = {"afghanistan":30.55, "albania":2.77,"algeria":39.21}
for key,value in world.items():
    print(key+" -- "+str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [41]:
for key in world:
    print(key)

afghanistan
albania
algeria


In [42]:
for value in world.values():
    print(value)

30.55
2.77
39.21


In [46]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight/np_height ** 2
for val in bmi:
    print(val)
bmi

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [49]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas = np.array([np_height,np_weight])
for val in meas:
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [54]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas = np.array([np_height,np_weight])
for val in np.nditer(meas):
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [3]:
import pandas as pd
brics = pd.read_csv("brics.csv", index_col=0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [4]:
brics = pd.read_csv("brics.csv", index_col=2)
brics

Unnamed: 0       country    area  population
capital                                               
Brasilia          BR        Brazil   8.516      200.40
Moscow            RU        Russia  17.100      143.50
New Delhi         IN         India   3.286     1252.00
Beijing           CH         China   9.597     1357.00
Pretoria          SA  South Africa   1.221       52.98

In [64]:
brics.iloc[0]

country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object

In [67]:
brics.loc["BR":"RU"]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5

In [70]:
for lab,row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [73]:
brics.country

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [74]:
for lab,row in brics.iterrows():
    print(lab+": "+row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [75]:
brics["capital"]

BR     Brasilia
RU       Moscow
IN    New Delhi
CH      Beijing
SA     Pretoria
Name: capital, dtype: object

In [76]:
brics.capital

BR     Brasilia
RU       Moscow
IN    New Delhi
CH      Beijing
SA     Pretoria
Name: capital, dtype: object

In [80]:
for lab,row in brics.iterrows():
    brics.loc[lab,"name_length"] = len(row["country"])
print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beijing   9.597     1357.00          5.0
SA  South Africa   Pretoria   1.221       52.98         12.0


In [81]:
brics["name_length"] = brics["country"].apply(len)
print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40            6
RU        Russia     Moscow  17.100      143.50            6
IN         India  New Delhi   3.286     1252.00            5
CH         China    Beijing   9.597     1357.00            5
SA  South Africa   Pretoria   1.221       52.98           12


In [5]:
brics["name_length"] = brics["country"].apply(len)
print(brics)

          Unnamed: 0       country    area  population  name_length
capital                                                            
Brasilia          BR        Brazil   8.516      200.40            6
Moscow            RU        Russia  17.100      143.50            6
New Delhi         IN         India   3.286     1252.00            5
Beijing           CH         China   9.597     1357.00            5
Pretoria          SA  South Africa   1.221       52.98           12


In [ ]:
.apply()