In [4]:
import numpy as np
np.ones(())

array(1.)

In [9]:
np.random.random(3)

array([0.63869821, 0.24680985, 0.64413536])

In [12]:
np.random.randint(3)

2

In [11]:
#solid works

In [ ]:
np.concatenate([x,y])

In [21]:
x = 2+4j
np.absolute(x) 
np.abs(x)
abs(x)

4.47213595499958

In [15]:
np.exp(1)

2.718281828459045

In [16]:
np.power(x,n) #x is base array, n is power

NameError: name 'n' is not defined

In [17]:
np.log(x)

(1.4978661367769956+1.1071487177940904j)

In [18]:
np.log2(x)

(2.1609640474436813+1.5972779646881086j)

In [19]:
np.log10(x)

(0.6505149978319906+0.4808285787842341j)

In [ ]:
np.arcsin(x)
np.arccos(x)
np.arctan(x)


In [ ]:
np.add.reduce(x)
np.multiply.reduce(x)
np.add.accumulate(x)
np.multiply.accumulate(x)
%timeit
min()
max()
np.min()
np.max()
.min()
.max()
.min(axis = 0) #each col
.min(axis = 1) #each row

.shape
.size
.ndim
.reshape((row,col))
np.concatenate([x,y]) # x and y are two arrays
np.sum()
np.prod()
np.any()
np.all()

In [26]:
var1 = np.random.randint(20,80,(4,3))
print(var1)
print(var1.shape)
print(var1.size)

[[31 28 37]
 [32 61 32]
 [73 65 47]
 [29 23 25]]
(4, 3)
12


In [27]:
var2 = np.random.randint(30,70,(4,3))
print(var2)
print(var2.shape)
print(var2.size)


[[43 55 59]
 [51 60 64]
 [62 46 69]
 [31 49 40]]
(4, 3)
12


In [29]:
np.hstack([var1,var2]) # horizontal concatenation # row wise

array([[31, 28, 37, 43, 55, 59],
       [32, 61, 32, 51, 60, 64],
       [73, 65, 47, 62, 46, 69],
       [29, 23, 25, 31, 49, 40]])

In [34]:
np.vstack([var1,var2]) # vertical concatenation # column wise

array([[31, 28, 37],
       [32, 61, 32],
       [73, 65, 47],
       [29, 23, 25],
       [43, 55, 59],
       [51, 60, 64],
       [62, 46, 69],
       [31, 49, 40]])

In [38]:
np.split(var1, 4)


[array([[31, 28, 37]]),
 array([[32, 61, 32]]),
 array([[73, 65, 47]]),
 array([[29, 23, 25]])]

In [52]:
varx = np.hsplit(var1, 3) # breaks column sie
print(varx)
print(varx[0])
varx[0][0]

[array([[31],
       [32],
       [73],
       [29]]), array([[28],
       [61],
       [65],
       [23]]), array([[37],
       [32],
       [47],
       [25]])]
[[31]
 [32]
 [73]
 [29]]


array([31])

In [53]:
np.vsplit(var1, 4) #breaks row wise

[array([[31, 28, 37]]),
 array([[32, 61, 32]]),
 array([[73, 65, 47]]),
 array([[29, 23, 25]])]

In [54]:
np.vsplit(var1,2)

[array([[31, 28, 37],
        [32, 61, 32]]),
 array([[73, 65, 47],
        [29, 23, 25]])]

In [58]:
np.add(x,2)
val1 = np.array(range(10))
print(val1)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
np.add(val1,4)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [62]:
# fancy command
np.add.reduce(val1) # works as np.sum

45

In [63]:
np.sum(val1)

45

In [64]:
np.multiply.reduce(val1)

0

In [65]:
np.add.accumulate(val1) 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [66]:
np.multiply.accumulate(val1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [68]:
valx = np.random.randint(100,500,size=8)
valx

array([164, 262, 393, 228, 282, 298, 205, 141])

In [69]:
min(valx)

141

In [70]:
np.min(valx)

141

In [76]:
%timeit min(valx)

1.55 µs ± 6.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [77]:
%timeit np.min(valx)

3.52 µs ± 16.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
%%timeit
import numpy as np
np.sum(valx)

3.44 µs ± 64.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [87]:
val1
var1 = np.random.randint(20,80,(6,4))

In [88]:
var1

array([[75, 52, 79, 22],
       [73, 51, 31, 68],
       [73, 20, 21, 58],
       [56, 31, 43, 24],
       [39, 78, 28, 72],
       [60, 70, 51, 60]])

In [89]:
var1[0].min()

22

In [90]:
np.min(var1[0])

22

In [91]:
var1.min(axis=1) #row wise minimum

array([22, 31, 20, 24, 28, 51])

In [92]:
var1.min(axis=0) #column wise minimum

array([39, 20, 21, 22])

In [ ]:
np.nansum()
np.nanprod()
np.argmin()
np.argmax()
np.median()
np.std()
np.mean()


In [96]:
valx

array([164, 262, 393, 228, 282, 298, 205, 141])

In [97]:
valx.argmin() # returns index of minimum argument
valx.argmax() # returns index of maximum argument

2

In [98]:
var1

array([[75, 52, 79, 22],
       [73, 51, 31, 68],
       [73, 20, 21, 58],
       [56, 31, 43, 24],
       [39, 78, 28, 72],
       [60, 70, 51, 60]])

In [110]:
np.any(valx>300) # checks values as per condition provided
valx[valx>300]

array([393])

In [111]:
np.all(var1>100)

False

In [112]:
# broadcasting. learn it

In [ ]:
np.equal(,)
np.not_equal(,)
np.less(,)
np.less_equal(,)
np.greater(,)
np.greater_equal(,)
np.random.randint(start,end,(row,column))
np.random.randint(start,end,size=n)
np.count_nonzero()

In [114]:
np.any(var1>20,axis=1) #axis =1 is for row. So it checks for rows that have > 20 value

array([ True,  True,  True,  True,  True,  True])

In [117]:
np.all(var1>20,axis=1)

array([ True,  True, False,  True,  True,  True])

In [118]:
np.all(var1>20,axis=0) #axis = 0 is for columns.

array([ True, False,  True,  True])

In [120]:
help(np.any)

Help on function any in module numpy:

any(a, axis=None, out=None, keepdims=<no value>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (``axis=None``) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the expected output and 

In [121]:
valx

array([164, 262, 393, 228, 282, 298, 205, 141])

In [122]:
valx[-1]

141

In [123]:
valx[1:4]

array([262, 393, 228])

In [125]:
#Fancy Indexing
ind = [0,2,4,6]
valx[ind]   #Giving indices on your own

array([164, 393, 282, 205])

In [126]:
valx[::2] # not fancy indexing. with step size

array([164, 393, 282, 205])

In [127]:
x = np.array([110,200,0,250,0])
x

array([110, 200,   0, 250,   0])

In [132]:
np.count_nonzero(x)

3

In [134]:
x.size - np.count_nonzero(x)

2

In [136]:
var1

array([[75, 52, 79, 22],
       [73, 51, 31, 68],
       [73, 20, 21, 58],
       [56, 31, 43, 24],
       [39, 78, 28, 72],
       [60, 70, 51, 60]])

In [138]:
np.sum(var1,axis=1) # row wise sum

array([228, 223, 172, 154, 217, 241])

In [139]:
np.sum(var1[0][:])

228

In [140]:
valx

array([164, 262, 393, 228, 282, 298, 205, 141])

In [141]:
min(valx)

141

In [142]:
max(valx)

393

In [144]:
min(valx[valx>300]) # manual way

393

In [148]:
#np.sum()
np.sum(valx[valx>300])

393

In [155]:
np.sum((valx>=200) & (valx<=300))

5

In [156]:
np.sum(~(valx>300)) #negation

7

In [ ]:
^ #xor symbol

In [157]:
valx

array([164, 262, 393, 228, 282, 298, 205, 141])

In [163]:
np.sort(valx)

array([141, 164, 205, 228, 262, 282, 298, 393])

In [159]:
sorted(valx, reverse=True)

[393, 298, 282, 262, 228, 205, 164, 141]

In [164]:
np.sort(~valx)

array([-394, -299, -283, -263, -229, -206, -165, -142], dtype=int32)

In [166]:
np.argsort(valx) #Giving actual indices of sorted arrays

array([7, 0, 6, 3, 1, 4, 5, 2], dtype=int64)