In [1]:
#Python Data Science Handbook Chapter 02 Numpy

import numpy
numpy.__version__

'1.18.5'

In [2]:
import numpy as np

In [3]:
np?

In [4]:
result = 0
for i in range(100):
    result +=i

In [5]:
L = list(range(10))

In [6]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [12]:
L3 = [True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [13]:
np.array([1,4,2,5,4])

array([1, 4, 2, 5, 4])

In [15]:
np.array([1,2,3,4], dtype= 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
# Irrational Numbers

np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.random.random((3,3))

array([[0.19082058, 0.56008242, 0.45443114],
       [0.09978451, 0.07574115, 0.69352039],
       [0.62337743, 0.05787855, 0.49066468]])

In [25]:
np.random.normal(0,1,(3,3))

array([[ 0.26973785, -1.22629861,  0.58890425],
       [-2.01433161, -0.01247303,  0.83260772],
       [ 0.16437693, -1.45936378, -0.68521448]])

In [32]:
np.random.randint(0,10,(3,3))

array([[4, 9, 6],
       [7, 5, 7],
       [4, 7, 9]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.empty(3)

array([1., 1., 1.])

In [34]:
np.empty(2)

array([  2.00000047, 512.00012255])

In [35]:
np.empty(3)

array([1., 1., 1.])