In [89]:
# https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/
# https://problemsolvingwithpython.com/02-Jupyter-Notebooks/02.07-Getting-Help-in-a-Jupyter-Notebook/
# https://www.google.com/search?q=help+command+jupyter+notebook&oq=help+command+j&aqs=chrome.1.69i57j0i457j0i22i30l5.3503j0j1&sourceid=chrome&ie=UTF-8

In [90]:
%timeit?

In [91]:
import math
help(math.sin)

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).



In [92]:
add?

Object `add` not found.


In [93]:
pd.read_csv? ## Execute this code with Shift+Enter

SyntaxError: invalid syntax (<ipython-input-93-f01a893c5fbb>, line 1)

In [ ]:
import numpy as np #Shift + Enter
a=np.random.randint #Shift + Tab working

In [ ]:
a=np.random.randint

In [ ]:
## Today Work

In [ ]:
import numpy as np
var1 = np.random.randint(20,80,(4,3))
print(var1)
print(var1.shape)
print(var1.size)

In [ ]:
var2 = np.random.randint(30,70,(4,3))  # (s,e,(r,c))
print(var2)
print(var2.shape)
print(var2.size)

In [ ]:
vv2 = np.hstack([var1,var2])

In [ ]:
np.size(vv2)

In [ ]:
np.vstack([var1,var2])

In [ ]:
varx = np.hsplit(var1,3)
varx

In [ ]:
varx[0]

In [ ]:
varx[0][0]

In [ ]:
varx[-1]

In [ ]:
var1

In [ ]:
np.vsplit(var1,4)

In [ ]:
np.vsplit(var1,2)

In [ ]:
import math
help(math.sin)

In [ ]:
val1 = np.array(range(10))
print(val1)
print(np.add(val1,4))
print(np.add.reduce(val1))   # Sum
np.sum(val1)
np.multiply.reduce(val1)

In [ ]:
np.add.accumulate(val1)

In [ ]:
np.multiply.accumulate(val1)

In [ ]:
valx = np.random.randint(100,500,size=8)
valx

In [ ]:
min(valx)

In [ ]:
np.min(valx)

In [ ]:
%timeit

In [ ]:
%timeit min(valx)
%timeit np.min(valx)

In [ ]:
%time np.min(valx)

In [ ]:
val1

In [ ]:
var1

In [ ]:
np.min(var1)

In [ ]:
var1 = np.random.randint(20,80,(6,4))
var1

In [ ]:
np.min(var1)

In [ ]:
var1.min(axis=1)   # row wise

In [ ]:
var1.min(axis = 0) # Col wise

In [ ]:
valx

In [ ]:
min(valx)

In [ ]:
valx.argmin()

In [ ]:
valx.argmax()

In [ ]:
var1

In [ ]:
var2

In [ ]:
np.any(valx > 400)

In [ ]:
np.any(data['col'] > 16)

In [ ]:
np.any(valx > 400)

In [ ]:
np.all(valx > 400)

In [ ]:
print(np.all(valx > 400))

In [ ]:
var1

In [ ]:
np.any(var1 > 20, axis=1)

In [ ]:
# (Axis:0 = Column , Axis:1 = Row)

np.all(var1>40, axis=0)

In [94]:
valx

array([310, 399, 279, 424, 266, 401, 324, 417])

In [95]:
valx[-1]

417

In [96]:
valx[1:4]

array([399, 279, 424])

In [97]:
ind = [0,2,4,6]
valx[ind]

array([310, 279, 266, 324])

In [98]:
valx[::2]

array([310, 279, 266, 324])

In [101]:
x = np.array([110,200,0,250,0])
x

array([110, 200,   0, 250,   0])

In [102]:
np.count_nonzero(x)

3

In [103]:
x.size - np.count_nonzero(x)

2

In [104]:
var1

array([[59, 22, 76, 47],
       [62, 26, 52, 26],
       [41, 20, 44, 71],
       [45, 73, 48, 37],
       [66, 40, 50, 68],
       [51, 24, 57, 21]])

In [105]:
np.count_nonzero?

In [106]:
np.sum(var1, axis= 1)

#axis = 0    {Column}
#axis = 1    {Row}

array([204, 166, 176, 203, 224, 153])

In [107]:
np.sum(var1[0][:])

204

In [110]:
min(valx)


266

In [109]:
max(valx)

424

In [111]:
#np.sum()
#np.sum(, axis =)
np.sum(valx>300)

6

In [112]:
np.sum(valx[valx>300])

2275

In [114]:
np.sum((valx>300))

6

In [116]:
np.sum((valx>=200) & (valx <=300))

2

In [117]:
np.sum(valx>300)

6

In [118]:
np.sum(~(valx>300))

2

In [119]:
# ^ Xor Function

In [120]:
valx

array([310, 399, 279, 424, 266, 401, 324, 417])

In [121]:
np.sort(valx)

array([266, 279, 310, 324, 399, 401, 417, 424])

In [123]:
np.sort

TypeError: _sort_dispatcher() got an unexpected keyword argument 'des'

In [124]:
# reverse_array = sorted_array[::-1]
sorted(valx, reverse=True)

[424, 417, 401, 399, 324, 310, 279, 266]

In [127]:
u=reverse_array = valx[::-1]
print(u)

[417 324 401 266 424 279 399 310]


In [129]:
np.argsort(valx)

# i) Sorting ascending
# ii) Telling their actual position

array([4, 2, 0, 6, 1, 5, 7, 3], dtype=int64)