In [1]:
1 == 1

True

In [2]:
1 != 1

False

In [3]:
'a' == 'A'

False

In [4]:
a = 2
b = 4
a != b

True

In [6]:
~b

-5

c = d = 50
c > d

In [7]:
c = 4
d = 50
c > d

False

In [8]:
a  = 3
b = 3
a >= 3

In [9]:
a = 'google'
b = 'google'

a == b

True

In [11]:
a = True
b = False



In [12]:
a > b

True

In [13]:
a != b

True

In [17]:
a = True       # 1
b = False      # 0

In [18]:
a and b

False

In [19]:
a or b

True

In [20]:
not a 

False

In [21]:
2 ==2 

True

In [22]:
2.0 == 2

True

In [23]:
3 > 2

True

In [24]:
3 < 2

False

In [25]:
x = 7


In [26]:
True == 1

True

In [28]:
False == 0

True

In [29]:
import numpy as np

my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0,14.25,9.0])

In [30]:
len(my_house)

4

In [31]:
my_house.shape

(4,)

In [32]:
my_house.size

4

In [ ]:
#Comparison operators with an array

In [33]:
print(my_house >= 18)

[ True  True False False]


In [34]:
print(my_house[my_house >= 18])  #IMPORTANT in PANDAS #MAGIC_WAND

[18. 20.]


In [36]:
print(my_house < your_house)

[False  True  True False]


In [37]:
print(my_house[my_house<your_house])

[20.   10.75]


In [38]:
new1 = my_house / 2
print(new1)

[ 9.    10.     5.375  4.75 ]


In [39]:
new2 = my_house + your_house
print(new2)

[32.  44.  25.  18.5]


In [40]:
# boolean operators (and, or, not)

In [42]:
#Define variables
my_kitchen = 18.0
your_kitchen = 14.0

In [43]:
print(my_kitchen > 10 and my_kitchen < 18)

False


In [44]:
print(my_kitchen > 10 or my_kitchen < 18)

True


In [45]:
not(3==3)

False

In [46]:
x = 8
y = 9

In [47]:
not(not(x<3) and not(y>14 or y>10))

False

In [48]:
my_house

array([18.  , 20.  , 10.75,  9.5 ])

In [49]:
my_house > 15

array([ True,  True, False, False])

In [50]:
my_house > 10

array([ True,  True,  True, False])

In [51]:
(my_house > 15) and (my_house > 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [52]:
np.logical_and(my_house > 15, my_house > 10)

array([ True,  True, False, False])

In [53]:
np.logical_or(my_house > 15, my_house > 10)

array([ True,  True,  True, False])

In [54]:
np.logical_not(my_house>15)

array([False, False,  True,  True])

In [55]:
# conditional statements
# if , else , elif


In [61]:
q = 2
if q>= 1:
    print('ok')
    print(2+4)
    print('house number '+ str(q))
    print('a')


ok
6
house number 2


In [64]:
q = 2
if q>= 1 :
    print('house number ' + str(q));
    print('a')

house number 2
a


In [65]:
q = 200
if q >= 400 :
    print('house number' + str(q));
    print('a')
else :
    print('qwerty')

qwerty


In [66]:
q = 0
if q > 1 :
    print('ok1')
elif q == 0:
    print('ok2')
elif q < 1:
    print('ok3')
else:
    print('ok4')

ok2


In [67]:
import pandas as pd

In [74]:
data = pd.read_csv('Country Capitals.csv' , index_col = 0)

In [75]:
data

country     capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china    beijing  456456     7891011
AG  afghanistan      kabul     123      123123

In [76]:
data

country     capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china    beijing  456456     7891011
AG  afghanistan      kabul     123      123123

In [77]:
a1 = data['capital'] 

In [78]:
a1

PK    islamabad
AU       sydney
IN    new delhi
CH      beijing
AG        kabul
Name: capital, dtype: object

In [81]:
data.loc['IN']

country           india
capital       new delhi
area               6789
population       789789
Name: IN, dtype: object

In [82]:
data.iloc[2]

country           india
capital       new delhi
area               6789
population       789789
Name: IN, dtype: object

In [83]:
data

country     capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china    beijing  456456     7891011
AG  afghanistan      kabul     123      123123

In [84]:
data.iloc[1:4]   #Slicing

country     capital    area  population
AU  australia     sydney     456      123456
IN      india  new delhi    6789      789789
CH      china    beijing  456456     7891011

In [85]:
#Dicing  picking alternate rows

data['capital']

PK    islamabad
AU       sydney
IN    new delhi
CH      beijing
AG        kabul
Name: capital, dtype: object

In [86]:
data['capital':'population']

KeyError: 'capital'

In [87]:
data

country     capital    area  population
PK     pakistan  islamabad     789      456789
AU    australia     sydney     456      123456
IN        india  new delhi    6789      789789
CH        china    beijing  456456     7891011
AG  afghanistan      kabul     123      123123

In [88]:
data.columns

Index(['country ', 'capital', 'area', 'population'], dtype='object')

In [89]:
data.index

Index(['PK', 'AU', 'IN', 'CH', 'AG'], dtype='object')

In [90]:
data.loc['PK']

country        pakistan
capital       islamabad
area                789
population       456789
Name: PK, dtype: object

In [91]:
data.iloc[0]

country        pakistan
capital       islamabad
area                789
population       456789
Name: PK, dtype: object

In [93]:
data.iloc[1:4]

country     capital    area  population
AU  australia     sydney     456      123456
IN      india  new delhi    6789      789789
CH      china    beijing  456456     7891011

In [94]:
data['area']

PK       789
AU       456
IN      6789
CH    456456
AG       123
Name: area, dtype: int64

In [95]:
data['area'] > 1000

PK    False
AU    False
IN     True
CH     True
AG    False
Name: area, dtype: bool

In [98]:
data[data['area'] > 1000]

country     capital    area  population
IN    india  new delhi    6789      789789
CH    china    beijing  456456     7891011