In [1]:
error = 50.0
while error > 1:
    error = error / 4
    print(error)

12.5
3.125
0.78125


In [3]:
z = 6
if z%2 ==0 : #True
    print("z is divisible by 2") #Executed
elif z % 3 == 0 :
    print("z is divisible by 3")
else:
    print("z is neither divisible by 2 or 3")

z is divisible by 2


In [4]:
fam = [1.73, 1.68, 1.71, 1.89]
print(fam)

[1.73, 1.68, 1.71, 1.89]


In [5]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
    print(height)

1.73
1.68
1.71
1.89


In [6]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
    print("index " + str(index) + ": "+ str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [7]:
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


In [9]:
world = {"afghanistan":30.55,"albania": 2.77,"algeria":39.21}
for key, value in world.items():
    print(key + " -- "+ str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [10]:
world = {"afghanistan":30.55,"albania": 2.77,"algeria":39.21}
for k, v in world.items():
    print(k + " -- "+ str(v))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [16]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight / np_height ** 2
for val in bmi :
    print(val)
  

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [17]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight / np_height ** 2
#for val in bmi :
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [18]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
means = np.array([np_height, np_weight])
for val in means :
    print(val)
  

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [19]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
means = np.array([np_height, np_weight])
for val in np.nditer(means) :
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [26]:
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)

In [27]:
data = brics

In [29]:
brics.loc['BR']

country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object

In [30]:
data.iloc[2]

country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object

In [31]:
for lab, row in brics.iterrows():          
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [32]:
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)
for lab, row in brics.iterrows():
    print(lab + ": " + row["capital"])         #Only Prints

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [33]:
brics['capital']    #Gives Dataframe

BR     Brasilia
RU       Moscow
IN    New Delhi
CH      Beijing
SA     Pretoria
Name: capital, dtype: object

In [35]:
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)
for lab, row in brics.iterrows():
# - Creating Series on every iteration
    brics.loc[lab,"name_length"] = len(row["country"])
print(brics)         

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beijing   9.597     1357.00          5.0
SA  South Africa   Pretoria   1.221       52.98         12.0


In [36]:
import pandas as pd
brics = pd.read_csv("brics.csv",index_col = 0)
brics["name_length"] = brics["country"].apply(len)
print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40            6
RU        Russia     Moscow  17.100      143.50            6
IN         India  New Delhi   3.286     1252.00            5
CH         China    Beijing   9.597     1357.00            5
SA  South Africa   Pretoria   1.221       52.98           12
